name: Release

on:
  push:
    branches:
      - main # Or your primary branch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        # Fetch all history so Changesets can determine changed packages
        with:
          fetch-depth: 0 

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use your project's node version
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Optional: Add build step if needed before versioning/publishing
      # - name: Build Packages
      #   run: pnpm turbo build --filter='!./apps/*' # Example: Build all packages except those in apps/

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This command will create a PR if changesets are present and run publish if on main/master
          # It automatically bumps versions, commits, tags, and publishes
          publish: pnpm publish -r --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Needs to be configured in repo secrets 